name: monti
channels:
  - weinbe58
  - conda-forge
  - anaconda
  - defaults
dependencies:
  - argon2-cffi=20.1.0=py37he774522_1
  - async_generator=1.10=py37h28b3542_0
  - attrs=20.2.0=py_0
  - backcall=0.2.0=py_0
  - blas=1.0=mkl
  - bleach=3.2.1=py_0
  - brotlipy=0.7.0=py37he774522_1000
  - ca-certificates=2020.10.14=0
  - certifi=2020.6.20=py37_0
  - cffi=1.14.3=py37h7a1dbc1_0
  - chardet=3.0.4=py37_1003
  - colorama=0.4.4=py_0
  - cryptography=3.1.1=py37h7a1dbc1_0
  - cycler=0.10.0=py37_0
  - decorator=4.4.2=py_0
  - defusedxml=0.6.0=py_0
  - dill=0.3.2=py_0
  - entrypoints=0.3=py37_0
  - freetype=2.10.4=hd328e21_0
  - gmpy2=2.0.8=py37h0964b28_3
  - icc_rt=2019.0.0=h0cc432a_1
  - icu=58.2=ha925a31_3
  - idna=2.10=py_0
  - imageio=2.9.0=py_0
  - importlib-metadata=2.0.0=py_1
  - importlib_metadata=2.0.0=1
  - intel-openmp=2020.2=254
  - ipykernel=5.3.4=py37h5ca1d4c_0
  - ipython=7.18.1=py37h5ca1d4c_0
  - ipython_genutils=0.2.0=py37_0
  - ipywidgets=7.5.1=py_1
  - jedi=0.17.2=py37_0
  - jinja2=2.11.2=py_0
  - joblib=0.17.0=py_0
  - jpeg=9b=hb83a4c4_2
  - jsonschema=3.2.0=py_2
  - jupyter=1.0.0=py37_7
  - jupyter_client=6.1.7=py_0
  - jupyter_console=6.2.0=py_0
  - jupyter_contrib_core=0.3.3=py_2
  - jupyter_contrib_nbextensions=0.5.1=py37hc8dfbb8_1
  - jupyter_core=4.6.3=py37_0
  - jupyter_highlight_selected_word=0.2.0=py37hc8dfbb8_1002
  - jupyter_latex_envs=1.4.6=py37hc8dfbb8_1001
  - jupyter_nbextensions_configurator=0.4.1=py37hc8dfbb8_2
  - jupyterlab_pygments=0.1.2=py_0
  - kiwisolver=1.2.0=py37h74a9793_0
  - libiconv=1.16=he774522_0
  - libpng=1.6.37=h2a8f88b_0
  - libsodium=1.0.18=h62dcd97_0
  - libtiff=4.1.0=h56a325e_1
  - libxml2=2.9.10=h1006b36_2
  - libxslt=1.1.33=h579f668_1
  - llvmlite=0.31.0=py37ha925a31_0
  - lxml=4.6.1=py37h8ba8a40_0
  - lz4-c=1.9.2=hf4a77e7_3
  - m2w64-gcc-libgfortran=5.3.0=6
  - m2w64-gcc-libs=5.3.0=7
  - m2w64-gcc-libs-core=5.3.0=7
  - m2w64-gmp=6.1.0=2
  - m2w64-libwinpthread-git=5.0.0.4634.697f757=2
  - markupsafe=1.1.1=py37hfa6e2cd_1
  - matplotlib=3.3.1=0
  - matplotlib-base=3.3.1=py37hba9282a_0
  - mistune=0.8.4=py37hfa6e2cd_1001
  - mkl=2020.2=256
  - mkl-service=2.3.0=py37hb782905_0
  - mkl_fft=1.2.0=py37h45dec08_0
  - mkl_random=1.1.1=py37h47e9c7a_0
  - mpc=1.1.0=h7edee0f_1
  - mpfr=4.0.2=h62dcd97_1
  - mpir=3.0.0=hec2e145_1
  - msys2-conda-epoch=20160418=1
  - nbclient=0.5.1=py_0
  - nbconvert=6.0.7=py37_0
  - nbformat=5.0.8=py_0
  - nest-asyncio=1.4.1=py_0
  - notebook=6.1.4=py37_0
  - numba=0.48.0=py37h47e9c7a_0
  - numexpr=2.7.1=py37h25d0782_0
  - numpy=1.19.1=py37h5510c5b_0
  - numpy-base=1.19.1=py37ha3acd2a_0
  - olefile=0.46=py37_0
  - openssl=1.1.1h=he774522_0
  - packaging=20.4=py_0
  - pandas=1.1.3=py37ha925a31_0
  - pandoc=2.11=h9490d1a_0
  - pandocfilters=1.4.2=py37_1
  - parso=0.7.0=py_0
  - pickleshare=0.7.5=py37_1001
  - pillow=8.0.0=py37hca74424_0
  - pip=20.2.4=py37_0
  - prometheus_client=0.8.0=py_0
  - prompt-toolkit=3.0.8=py_0
  - prompt_toolkit=3.0.8=0
  - pycparser=2.20=py_2
  - pygments=2.7.1=py_0
  - pyopenssl=19.1.0=py_1
  - pyparsing=2.4.7=py_0
  - pyqt=5.9.2=py37h6538335_2
  - pyrsistent=0.17.3=py37he774522_0
  - pysocks=1.7.1=py37_1
  - python=3.7.9=h60c2a47_0
  - python-dateutil=2.8.1=py_0
  - python_abi=3.7=1_cp37m
  - pytz=2020.1=py_0
  - pywin32=227=py37he774522_1
  - pywinpty=0.5.7=py37_0
  - pyyaml=5.3.1=py37h0013d47_1
  - pyzmq=19.0.2=py37ha925a31_1
  - qt=5.9.7=vc14h73c81de_0
  - qtconsole=4.7.7=py_0
  - qtpy=1.9.0=py_0
  - quspin=0.3.4=py37h45f375f_1
  - qutip=4.5.2=py37h742c72c_0
  - requests=2.24.0=py_0
  - scipy=1.5.2=py37h9439919_0
  - send2trash=1.5.0=py37_0
  - setuptools=50.3.0=py37h9490d1a_1
  - sip=4.19.8=py37h6538335_0
  - six=1.15.0=py_0
  - sqlite=3.33.0=h2a8f88b_0
  - tbb=2020.3=h74a9793_0
  - terminado=0.9.1=py37_0
  - testpath=0.4.4=py_0
  - tk=8.6.10=he774522_0
  - tornado=6.0.4=py37he774522_1
  - tqdm=4.50.2=py_0
  - traitlets=5.0.5=py_0
  - urllib3=1.25.11=py_0
  - vc=14.1=h0510ff6_4
  - vs2015_runtime=14.16.27012=hf0eaf9b_3
  - wcwidth=0.2.5=py_0
  - webencodings=0.5.1=py37_1
  - wheel=0.35.1=py_0
  - widgetsnbextension=3.5.1=py37_0
  - win_inet_pton=1.1.0=py37_0
  - wincertstore=0.2=py37_0
  - winpty=0.4.3=4
  - xz=5.2.5=h62dcd97_0
  - yaml=0.2.5=he774522_0
  - zeromq=4.3.2=ha925a31_3
  - zipp=3.3.0=py_0
  - zlib=1.2.11=h62dcd97_4
  - zstd=1.4.5=h04227a9_0
  - pip:
    - cython==0.29.21
    - gif==3.0.0
    - qsp-opti==1.0
prefix: C:\Users\GUIDA\anaconda3\envs\monti

